---
- name: Setup BIGD on Alpine
  hosts: node1 # see hosts.i:w
  become: true
  become_user: root
  become_method: sudo  
  gather_facts: False # if no Python on target machine

  vars:
    - username: alpine
    - password: alpine
    - apk_packages: [findutils, curl, openjdk8, openssh, ruby, bash,
                      cracklib-words, supervisor, procps]
  tasks:
  - apk:  # install apk packages
     name: "{{ item }}"
     update_cache: yes
    with_items: "{{ apk_packages }}"
  - name: Delete apk cache
    file: 
     path: /var/cache/apk/*
     state: absent

