---
- name: Setup BIGD on Alpine
  hosts: node1 # see hosts.i:w
  become: true
  become_user: root
  become_method: sudo  
  gather_facts: False # if no Python on target machine

  vars:
    - username: alpine
    - password: alpine
    - apk_packages: [findutils, curl, openjdk8, openssh, ruby, bash,
                      cracklib-words, supervisor, procps]
    - hadoop_version: "3.1.1"
    - hadoop_home: "/usr/local/hadoop"
    - hadoop_src: "https://archive.apache.org/dist/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
    - hadoop_config_files: [core-site.xml, hdfs-site.xml, mapred-site.xml, yarn-site.xml]

  tasks:
  - apk:  # install apk packages
     name: "{{ item }}"
     update_cache: yes
    with_items: "{{ apk_packages }}"
  - name: Delete apk cache
    file: 
     path: /var/cache/apk/*
     state: absent
  # maybe add sed etc later
  # - name: Download Hadoop
  # shell: curl {{ hadoop_src }}
  # TODO: unpack
  - name: Copy local env.sh to /etc/profile.d/env.sh
    copy:
     src: env.sh
     dest: /etc/profile.d/env.sh 
  - name: Write /etc/hadoop/hadoop-env.sh
    shell: echo "export JAVA_HOME=$(readlink -f /usr/bin/java | sed 's:/jre/bin/java::')" >> {{ hadoop_home }}/etc/hadoop/hadoop-env.sh
  - name: Copy local supervisord.conf to /etc/supervisord.conf
    copy:
     src: supervisord.conf
     dest: /etc/supervisord.conf
  - name: Copy Hadoop configuration files
    copy:
     src: "{{ item }}"
     dest: "/usr/local/hadoop/etc/hadoop/{{ item }}"
    with_items: "{{ hadoop_config_files }}"
 

